### ISSUE TITLE
0.7版本默认编辑器自动转换相对图片路径可能造成的bug

### ISSUE THREAD

**Issue by PiouseLeo** [xuming/micolog#4]
Hi， 

我在使用0.7版本的micolog，发现一个小问题，就是我在使用默认的编辑器加入图片的时候，如果我的图片地址为： 

http://xxx.appsopt.com/media/abc.jpg 

那么在插入后，编辑器会自动将其转化为相对路径../media/abc.jpg，（这样做或许是为了节省几个字节？） 

由于相对路径的原因，我在首页访问时，图片可以正常显示。但是如果我进入文章页面（设置了slub的情况），那么当前的路径就会变为： 
http://xxx.appspot.com/2010/12/5/xxx.html 
由于当前路径变为了/2010/12/5/，所以图片的实际获取路径就变为了：/2010/12/media/abc.jpg，造成404。 

建议去掉自动转相对图片路径的功能。

**Comment by tweet** [comment]
编辑器Tinymce问题，我看了一下，最新的代码已经改过来了啊
relative_urls: false
或者你可以自己手动添加
micolog\views\admin\entry.html
的$('#content').tinymce({})初始化里面添加 “ relative_urls: false
 ”即可
