### ISSUE TITLE
博客标题在写入到页面之前应该做HTML escape

### ISSUE THREAD

**Issue by PiouseLeo** [xuming/micolog#6]
RT,假如我的标题中有HTML敏感的字符，比如单双引号",'等，那么就会出现无法预计的bug，或者无法通过XHTML的语法验证。

这个变更是有必要的，因为博客标题可能是"XXX’s Blog"等。

**Comment by tweet** [comment]
你可以直接在模板中添加escape过滤器就可以了

**Comment by linin** [comment]
我认为服务器端还是有必要对可能存在的所有问题检查一遍，因为有可能会在不支持JS的电脑的用Blog。
